In [1]:
import tensorflow as tf

In [2]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0, tf.float32)
n1= 3
n2=4

In [3]:
print (node1, node2)

(<tf.Tensor 'Const:0' shape=() dtype=float32>, <tf.Tensor 'Const_1:0' shape=() dtype=float32>)


In [4]:
print (n1, n2)

(3, 4)


In [5]:
sess = tf.Session()
sess.run([node1, node2])

[3.0, 4.0]

In [6]:
node1

<tf.Tensor 'Const:0' shape=() dtype=float32>

In [7]:
node3 = tf.add(node1, node2)
print (node3)

Tensor("Add:0", shape=(), dtype=float32)


In [8]:
sess.run([node3])

[7.0]

In [10]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b

In [11]:
a

<tf.Tensor 'Placeholder_2:0' shape=<unknown> dtype=float32>

In [12]:
b

<tf.Tensor 'Placeholder_3:0' shape=<unknown> dtype=float32>

In [13]:
adder_node

<tf.Tensor 'add:0' shape=<unknown> dtype=float32>

In [14]:
sess.run(adder_node, {a: 3, b:4.5})

7.5

In [20]:
sess.run(adder_node, {a: [3,2,1], b:[4.5]})

array([ 7.5,  6.5,  5.5], dtype=float32)

In [21]:
add_and_triple = adder_node * 3

In [22]:
sess.run(add_and_triple, {a: 3, b: 4})

21.0

In [23]:
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x= tf.placeholder(tf.float32)

In [24]:
w

<tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>

In [25]:
b

<tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>

In [26]:
x

<tf.Tensor 'Placeholder_4:0' shape=<unknown> dtype=float32>

In [27]:
linear_model = w*x + b

In [28]:
linear_model

<tf.Tensor 'add_1:0' shape=<unknown> dtype=float32>

In [29]:
init = tf.global_variables_initializer()
sess.run(init)

In [30]:
sess.run(linear_model, {x:[1, 2, 3, 4, 5]})

array([ 0.        ,  0.30000001,  0.60000002,  0.90000004,  1.20000005], dtype=float32)

In [31]:
y = tf.placeholder(tf.float32)

In [32]:
squared_error = tf.square(linear_model - y)

In [33]:
sum_squared_error = tf.reduce_sum(squared_error)

In [34]:
sess.run(sum_squared_error, {x: [1, 2, 3, 4, 5], y: [10, 12, 13, 14, 15]})

752.70001

In [52]:
# w = tf.assign(w, [1.])
# b = tf.assign(b, [10.])
# sess.run([w, b])

In [45]:
sess.run(sum_squared_error, {x: [1, 2, 3, 4, 5], y: [11, 12, 13, 14, 15]})

0.0

In [46]:
sess.run(linear_model, {x: [1, 2, 3, 4, 5]})

array([ 11.,  12.,  13.,  14.,  15.], dtype=float32)

In [47]:
optimizer = tf.train.GradientDescentOptimizer(0.01)

In [48]:
train_step = optimizer.minimize(sum_squared_error)

In [58]:
sess.run(init)

In [59]:
sess.run(train_step, {x: [1, 2, 3, 4, 5], y: [11, 12, 13, 14, 15]})

In [60]:
sess.run([w, b])

[array([ 1.], dtype=float32), array([ 10.], dtype=float32)]